messages:
  duels-command-usage: ""


properties:
  death-messages: false
  # if true, player on joining server will receive items for joining or creating duel
  give-duel-items-on-join: true
  # if true, player won't be able to move duel items from specified slots, drop 'em or anything.
  inventory-lock-duel-items: true
  # item for joining duels
  duel-join:
    # slot on which item will be set
    slot: 0
    item:
      # itemstack
      ==: org.bukkit.inventory.ItemStack
      v: 2230
      type: DIAMOND_SWORD
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Join duels item!"
  # item for creating duel
  duel-create:
    # slot on which item will be set
    slot: 8
    item:
      # itemstack
      ==: org.bukkit.inventory.ItemStack
      v: 2230
      type: SHIELD
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Create own duel!"


# arenas
arenas:
  1:
    # name of arena
    name: "Wild West"
    # icon of arena in gui
    icon:
      ==: org.bukkit.inventory.ItemStack
      v: 2230
      type: DIAMOND_SWORD
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Wild west"
    # time in seconds
    time-limit: 60
    properties:
      # ability to damage players from the same team
      friendly-damage: true
      # allows to destroy block on arena, if you want to specify blocks check {destroy-allowlist}
      allow-destroy: true
      # drop player equipment on death
      drop-equipment-on-death: true
      # force drop death player equipment to killer inventory ( needs {drop-equipment-on-death} true )
      drop-equipment-to-inventory: false
      # list of block to destroy, if list empty == can destroy all
      destroy-allowlist:
        - "DIRT"
        - "GLASS"
    # starting equipment applied for each player on arena start
    starting-equipment:
      # starting potion effects applied on arena start, in format: PotionEffectEnum, Amplifier, Duration(in sec)
      starting-effects:
        - "SPEED:2:60"
      # items given for players
      starting-items:
        # slot in inventory
        0:
          # itemstack
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: DIAMOND_SWORD
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: "Wild west"
    # spawning points, every point == 1 team
    #    NORTH
    #    EAST
    #    SOUTH
    #    WEST
    #    UP
    #    DOWN
    #    NORTH_EAST(NORTH, EAST),
    #    NORTH_WEST(NORTH, WEST),
    #    SOUTH_EAST(SOUTH, EAST),
    #    SOUTH_WEST(SOUTH, WEST),
    #    WEST_NORTH_WEST(WEST, NORTH_WEST),
    #    NORTH_NORTH_WEST(NORTH, NORTH_WEST),
    #    NORTH_NORTH_EAST(NORTH, NORTH_EAST),
    #    EAST_NORTH_EAST(EAST, NORTH_EAST),
    #    EAST_SOUTH_EAST(EAST, SOUTH_EAST),
    #    SOUTH_SOUTH_EAST(SOUTH, SOUTH_EAST),
    #    SOUTH_SOUTH_WEST(SOUTH, SOUTH_WEST),
    #    WEST_SOUTH_WEST(WEST, SOUTH_WEST),
    #    SELF
    spawning-points:
      1:
        world: "world"
        x: 0
        y: 60
        z: 0
        direction: NORTH
      2:
        world: "world"
        x: 0
        y: 60
        z: 0
        direction: SOUTH
      3:
        world: "world"
        x: 0
        y: 60
        z: 0
        direction: WEST
      4:
        world: "world"
        x: 0
        y: 60
        z: 0
        direction: EAST